### ISSUE TITLE
Add "I" and "Contract" to the lookup

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/interfaces#1]
currently contracts are identified when they end with `Interface` like `AuthenticationInterface` but they should also be identified when they end with `Contract` like `AuthenticationContract` or start with the letter `I` like `IAuthentication`.

The I part may get tricky because it will conflict with things like a base class of `Igloo` so maybe we can do another check somehow with that one.

**Comment by Marlysson** [comment]
Where do we find the `Igloo` class that could be conflicting?

**Comment by josephmancuso** [comment]
Yeah it’s gonna be a problem. The only reason to put the I in front is when you come from languages like Java where all interfaces have an I in front

**Comment by Marlysson** [comment]
But inherit from `Interface` base class isn't enough to handle it as the `interface`?

**Comment by josephmancuso** [comment]
don't think this is possible
