### ISSUE TITLE
Disable this somehow for production

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/interfaces#2]
This does a lot of calculations so we need to be able to disable this somehow.

For example, this should really only be enforced during development and then when you move to a production environment it should be disabled. We don't want to enforce any checks on production environments.

**Comment by psyonara** [comment]
Could a check on ```settings.DEBUG``` suffice for this?

**Comment by josephmancuso** [comment]
It could for Django right? Is there a way to check for global settings on any python project? I don’t really want to do 10 checks for 10 different frameworks way of setting debug modes ..🤔

**Comment by psyonara** [comment]
Haha, sorry, my thinking always defaults to Django. Of course, it would need something that is framework agnostic. Thinking about it some more now, I can only see this working by checking an environment variable. Would you say that it needs to be disabled by default, and then the developer sets a env var to specifically enable it in their development environment? Then the default is already correct for production environments, and the developer doesn't need to worry about making sure it's off in production. But that would also require one extra step to get it set up when you start to implement it during development.

**Comment by josephmancuso** [comment]
yeah it should definitely be enabled by default but an environment variable is actually a really good idea. something like `ENABLE_INTERFACES` and we can turn it on or off (even in development)

**Comment by psyonara** [comment]
Cool, I could take a look at this then, if you like. I should be able to make some time for it this week.

**Comment by josephmancuso** [comment]
sounds good to me 👍 let me know if you need help

**Comment by psyonara** [comment]
@josephmancuso Will the new environment variable completely replace the check for ```application.DEBUG```, or do you want to keep that in there, and use it in combination with ```ENABLE_INTERFACES```?

**Comment by josephmancuso** [comment]
ummmmmmmm. yes. I'd like sort of "first class support" for Masonite but it's fine. 

So yes replace that check if the ENABLE_INTERFACES check.

Keep in mind though that I'm pretty sure you need to do a string check if it's true. Environment variables will always be strings.

**Comment by psyonara** [comment]
Actually I think Masonite support can be preserved. So if it's being used as part of Masonite, and the new env var is either not defined, or marked as enabled, we can keep the DEBUG check. So then Masonite users will not have to do anything additional.

Anyway, will give it a try, and see what I can come up with. :)

**Comment by josephmancuso** [comment]
Sounds good to me but it will be a little tricky because that check needs to be outside of the try catch block I would think

**Comment by psyonara** [comment]
I have some ideas. :)
